# Generated by Django 3.1 on 2021-02-22 09:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quest', '0003_auto_20210222_0826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidatoparametro',
            name='candidato',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
