# Generated by Django 3.1 on 2021-03-05 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quest', '0005_auto_20210226_0951'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='stato',
            field=models.PositiveSmallIntegerField(choices=[(1, 'RegistrazioneAnagraficaStep'), (2, 'EsperienzeStudiStep')], default=1),
        ),
    ]
