# Generated by Django 3.1 on 2021-03-12 10:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quest', '0006_myuser_stato'),
    ]

    operations = [
        migrations.CreateModel(
            name='Previsione',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previsione', models.DecimalField(decimal_places=2, max_digits=5)),
                ('esito', models.BooleanField()),
                ('candidato', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'previsione_corrente',
                'verbose_name_plural': 'previsioni_corrente',
                'db_table': 'previsione_corrente',
            },
        ),
    ]
