# Generated by Django 3.1 on 2021-03-12 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quest', '0007_previsione'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='myuser',
            managers=[
            ],
        ),
    ]
