# Generated by Django 3.1 on 2021-04-29 19:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('quest', '0009_auto_20210429_1902'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aziendalingua',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='aziendalingua',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='candidatoparametro',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='candidatoparametro',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
