# Generated by Django 3.1 on 2021-05-11 12:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quest', '0010_auto_20210429_1904'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ambito',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Lavoro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('ambito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quest.ambito')),
            ],
        ),
        migrations.AddField(
            model_name='esperienza',
            name='ambito',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='quest.ambito'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='esperienza',
            name='professione',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='quest.lavoro'),
        ),
    ]
