# Generated by Django 3.1 on 2021-05-11 12:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quest', '0011_auto_20210511_1217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='esperienza',
            name='ambito',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='quest.ambito'),
        ),
        migrations.AlterField(
            model_name='esperienza',
            name='professione',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='quest.lavoro'),
        ),
    ]
