# Generated by Django 3.1 on 2021-05-22 09:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quest', '0012_auto_20210511_1237'),
    ]

    operations = [
        migrations.CreateModel(
            name='Amm1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Amm2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, unique=True)),
                ('amm1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quest.amm1')),
            ],
        ),
        migrations.CreateModel(
            name='Amm3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, unique=True)),
                ('amm2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quest.amm2')),
            ],
        ),
        migrations.CreateModel(
            name='Amm4',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, unique=True)),
                ('amm3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quest.amm3')),
            ],
        ),
        migrations.CreateModel(
            name='Amm5',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('amm4', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quest.amm4')),
            ],
        ),
        migrations.CreateModel(
            name='CandidatoEsperienza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=124)),
            ],
        ),
        migrations.CreateModel(
            name='CandidatoResidenza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=124)),
                ('amm1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='quest.amm1')),
                ('amm2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='quest.amm2')),
                ('amm3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='quest.amm3')),
                ('amm4', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='quest.amm4')),
                ('amm5', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='quest.amm5')),
            ],
        ),
        migrations.CreateModel(
            name='Professione',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Settore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
            ],
        ),
        migrations.RemoveField(
            model_name='lavoro',
            name='ambito',
        ),
        migrations.RemoveField(
            model_name='anagrafica',
            name='comune',
        ),
        migrations.RemoveField(
            model_name='anagrafica',
            name='provincia',
        ),
        migrations.RemoveField(
            model_name='anagrafica',
            name='stato',
        ),
        migrations.DeleteModel(
            name='Esperienza',
        ),
        migrations.DeleteModel(
            name='Lavoro',
        ),
        migrations.AddField(
            model_name='professione',
            name='settore',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quest.settore'),
        ),
        migrations.AddField(
            model_name='candidatoesperienza',
            name='professione',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='quest.professione'),
        ),
        migrations.AddField(
            model_name='candidatoesperienza',
            name='settore',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='quest.settore'),
        ),
    ]
