# Generated by Django 3.1 on 2021-06-11 08:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quest', '0013_auto_20210522_0918'),
    ]

    operations = [
        migrations.AddField(
            model_name='amm1',
            name='lingua',
            field=models.ForeignKey(default= 1, on_delete=django.db.models.deletion.CASCADE, to='quest.lingua'),
            preserve_default=False,
        ),
    ]
