# Generated by Django 3.1 on 2021-06-15 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quest', '0015_auto_20210615_1401'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='amm1',
            name='lingua',
        ),
    ]
